services:
  postgres:
    image: postgres:16
    container_name: llm-chatbot
    environment:
      POSTGRES_DB: llm-chatbot
      POSTGRES_USER: llm-chatbot
      POSTGRES_PASSWORD: llm-chatbot
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

